site_name: Vizz Cyber Field Notes
site_description: Pentester's diary
docs_dir: notes
site_dir: site

theme:
  name: gitbook
  language: en

nav:
  - Home: index.md
  - Android Pentesting: android.md

extra_css:
  - _assets/styles.css

